### ISSUE TITLE
Mixes of contours and components don't work

### ISSUE THREAD

**Issue by jbmorizot** [andyclymer/InterpolationSlider-RoboFontExt#1]
If you don't want to draw mixed glyphs, maybe a try pass could avoid the extension to bug in this particular case?

**Comment by andyclymer** [comment]
@jbmorizot Good catch! I changed it so that it will now decompose components before interpolating, borrowing some code from here: https://github.com/robotools/fontParts/issues/399

It should already show up in Mechanic 2 as version 1.3

**Comment by jbmorizot** [comment]
@andyclymer Perfect, thanks!
